/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package examen;

import java.util.ArrayList;

import examen.expl.Ejemplo;
import examen.expl.Multimedia;
import examen.lib.LibConf;
import examen.lib.LibInput;
import examen.lib.LibMenu;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
      //Ejemplo ejemplo = new Ejemplo();
        LibMenu.printEnum(Enums.values());
        


    }
}
